### ISSUE TITLE
Plugin returns 503 status code even if the services are up

### ISSUE THREAD

**Issue by niksoni** [pingidentity/status-servlet#3]
I installed this plugin on PingDirectory Server, it should return Status code 200 if Server is up and running, but it is returning a 503 status code instead with the “Server”:”available” message in the body. I followed exact steps provided to install this plugin. Could you please let me know how to fix this?

Thanks,
Nikhil

**Comment by braveulysses** [comment]
Try removing any extension argument for monitored-servlet. E.g.:

```
dsconfig set-http-servlet-extension-prop --extension-name Status \
  --remove extension-argument:monitored-servlet=OAuth2 \
  --remove extension-argument:monitored-servlet=SCIM2 \
  --remove extension-argument:monitored-servlet=UserInfo \
  --remove extension-argument:monitored-servlet=JWK
```

This extension was originally written for the Data Broker product and was later updated so that it could be used with the Directory Server, so the example configuration in the README isn't correct for the DS. I'll update the README when I have a chance.

**Comment by niksoni** [comment]
Thank you so much! This resolved the issue.
